//go:build ignore

// Generates the syntax-highlighting CSS block for static/style.css.
//
//	go run scripts/gen-chroma-css.go > /tmp/chroma.css
//
// Chroma can bake colours into inline style attributes, but then a code block
// is stuck on one palette forever. Emitting classes and generating the colours
// here lets the same markup follow the site's light/dark theme, using the
// selectors style.css already uses everywhere else.
package main

import (
	"bufio"
	"fmt"
	"os"
	"regexp"
	"strings"

	chromahtml "github.com/alecthomas/chroma/v2/formatters/html"
	"github.com/alecthomas/chroma/v2/styles"
)

var comment = regexp.MustCompile(`/\*.*?\*/`)

// emit prefixes every rule so a palette only applies under its own theme.
func emit(style string, scopes []string) string {
	s := styles.Get(style)
	if s == nil {
		panic("unknown chroma style: " + style)
	}
	f := chromahtml.New(chromahtml.WithClasses(true), chromahtml.ClassPrefix("chroma-"))
	var raw strings.Builder
	if err := f.WriteCSS(&raw, s); err != nil {
		panic(err)
	}
	var out strings.Builder
	sc := bufio.NewScanner(strings.NewReader(raw.String()))
	for sc.Scan() {
		// Chroma labels each rule with an inline /* Token */ comment ahead of
		// the selector. Strip it, or it ends up glued into the selector and
		// every generated rule silently matches nothing.
		line := strings.TrimSpace(comment.ReplaceAllString(sc.Text(), ""))
		if line == "" {
			continue
		}
		// Chroma writes one rule per line: "selector { decls }".
		open := strings.Index(line, "{")
		if open < 0 {
			continue
		}
		sel := strings.TrimSpace(line[:open])
		body := line[open:]
		// Container-level rules carry Chroma's own background and text sizing.
		// Drop them: style.css already gives code blocks their surface, and
		// Chroma's grey would sit on top of the theme's.
		if sel == ".chroma-chroma" || sel == ".chroma-bg" {
			continue
		}
		var parts []string
		for _, one := range strings.Split(sel, ",") {
			one = strings.TrimSpace(one)
			for _, sc := range scopes {
				parts = append(parts, sc+" "+one)
			}
		}
		fmt.Fprintf(&out, "%s %s\n", strings.Join(parts, ",\n"), body)
	}
	return out.String()
}

func main() {
	w := os.Stdout
	fmt.Fprintln(w, "/* Syntax highlighting — generated by scripts/gen-chroma-css.go, do not hand-edit. */")
	fmt.Fprintln(w, "/* light */")
	fmt.Fprint(w, emit("github", []string{":root", `[data-theme="light"]`}))
	fmt.Fprintln(w, "/* dark */")
	fmt.Fprint(w, emit("github-dark", []string{`[data-theme="dark"]`}))
	fmt.Fprintln(w, `@media (prefers-color-scheme: dark) {`)
	fmt.Fprint(w, emit("github-dark", []string{`:root:not([data-theme="light"])`}))
	fmt.Fprintln(w, "}")
}
